# Generated by Django 4.2.1 on 2023-05-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sky_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='store_views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(unique=True)),
                ('pg_views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Просмотры страницы',
                'verbose_name_plural': 'Просмотры',
            },
        ),
    ]
