# Generated by Django 4.2.1 on 2023-05-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sky_store', '0002_store_views'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='store_views',
            new_name='StoreView',
        ),
    ]
