# Generated by Django 4.2.1 on 2023-05-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sky_store', '0003_rename_store_views_storeview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField()),
                ('view_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StoreView',
        ),
    ]
