# Generated by Django 4.2.1 on 2023-06-12 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sky_store', '0007_alter_product_options_alter_product_id_prodversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodversion',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 10, 32, 16, 133857, tzinfo=datetime.timezone.utc)),
        ),
    ]
