# Generated by Django 4.2.1 on 2023-06-12 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sky_store', '0008_prodversion_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='version_cur',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='prodversion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
