# Generated by Django 4.2.1 on 2023-06-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sky_store', '0009_product_version_cur_alter_prodversion_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='version_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
