# Generated by Django 4.2.1 on 2023-06-12 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sky_store', '0010_product_version_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_ed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_mk',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
