# Generated by Django 4.2.1 on 2023-06-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Подтвержденный адрес'),
        ),
        migrations.AddField(
            model_name='user',
            name='verif_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
